### ISSUE TITLE
There is a problem with the document format detected by pydocstyle.

### ISSUE THREAD

**Issue by houxiyao** [kozhushman/pydocstring#6]
### Example:
pydocstype(D200): One-line docstring should fit on one line with quotes.
> For functions with no parameters.
```Python
No:
def func_name():
    """
    Description of func_name

    """
    ...

Yes:
def func_name():
    """Description of func_name."""
    ...
```

**Comment by kozhushman** [comment]
Thanks!
I`ll try to update it after work :)

**Comment by kozhushman** [comment]
Sorry it took so long, it was very busy time.
